name: integration_spec
description: Generate Page Object Model dart class by spec.yml
version: 0.0.2
homepage: https://github.com/prongbang/integration_spec

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  yaml: ^3.1.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0