name: integration_testgen
description: Generate Page Object Model dart class by spec.yml
version: 2.0.1
homepage: https://github.com/prongbang/integration_testgen

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  yaml: ^3.1.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0